// <auto-generated />
using System;
using AnuradhapuraAI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnuradhapuraAI.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AnuradhapuraAiDbContext))]
    [Migration("20261007105741_AddCropRequirementScoringMetadata")]
    partial class AddCropRequirementScoringMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnuradhapuraAI.Domain.Entities.Crop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Crop", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Paddy"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Maize"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Green Gram"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Cowpea"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Groundnut"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Chilli"
                        });
                });

            modelBuilder.Entity("AnuradhapuraAI.Domain.Entities.CropEnvironmentalRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AcceptableMaximumValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("AcceptableMinimumValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CropId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCompatibleWithSevenDayForecast")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("MaximumValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MinimumValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TimeBasis")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VariableType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CropId", "VariableType")
                        .IsUnique();

                    b.ToTable("CropEnvironmentalRequirement", null, t =>
                        {
                            t.HasCheckConstraint("CK_CropEnvironmentalRequirement_AcceptableOptimalOrdering", "[AcceptableMinimumValue] IS NULL OR ([AcceptableMinimumValue] <= [MinimumValue] AND [MaximumValue] <= [AcceptableMaximumValue])");

                            t.HasCheckConstraint("CK_CropEnvironmentalRequirement_MinimumMaximum", "[MinimumValue] <= [MaximumValue]");

                            t.HasCheckConstraint("CK_CropEnvironmentalRequirement_TimeBasis", "[TimeBasis] IS NULL OR [TimeBasis] IN (N'Daily', N'SevenDay', N'GrowingPeriod', N'Seasonal', N'Annual')");

                            t.HasCheckConstraint("CK_CropEnvironmentalRequirement_VariableType", "[VariableType] IN (N'Rainfall', N'Temperature', N'Humidity')");
                        });
                });

            modelBuilder.Entity("AnuradhapuraAI.Domain.Entities.ForecastRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("ForecastDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Humidity")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Rainfall")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateOnly>("TargetDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Temperature")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ForecastDate", "TargetDate");

                    b.ToTable("ForecastRecord", (string)null);
                });

            modelBuilder.Entity("AnuradhapuraAI.Domain.Entities.Recommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Recommendation", (string)null);
                });

            modelBuilder.Entity("AnuradhapuraAI.Domain.Entities.RecommendationCrop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CropId")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("HumidityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("OverallScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("RainfallScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("RecommendationId")
                        .HasColumnType("int");

                    b.Property<decimal>("SoilScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("SuitabilityCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TemperatureScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("CropId");

                    b.HasIndex("RecommendationId", "CropId")
                        .IsUnique();

                    b.HasIndex("RecommendationId", "Rank")
                        .IsUnique();

                    b.ToTable("RecommendationCrop", null, t =>
                        {
                            t.HasCheckConstraint("CK_RecommendationCrop_SuitabilityCategory", "[SuitabilityCategory] IN (N'Highly Suitable', N'Suitable', N'Moderately Suitable', N'Unsuitable')");
                        });
                });

            modelBuilder.Entity("AnuradhapuraAI.Domain.Entities.RecommendationValidation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("OfficerUserId")
                        .HasColumnType("int");

                    b.Property<int>("RecommendationId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("OfficerUserId");

                    b.HasIndex("RecommendationId");

                    b.ToTable("RecommendationValidation", null, t =>
                        {
                            t.HasCheckConstraint("CK_RecommendationValidation_Status", "[Status] IN (N'Pending Validation', N'Validated', N'Needs Review')");
                        });
                });

            modelBuilder.Entity("AnuradhapuraAI.Domain.Entities.SoilCompatibility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CompatibilityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("CropId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SoilType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CropId", "SoilType")
                        .IsUnique();

                    b.ToTable("SoilCompatibility", (string)null);
                });

            modelBuilder.Entity("AnuradhapuraAI.Domain.Entities.SuitabilityConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigurationKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConfigurationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("ConfigurationType", "ConfigurationKey")
                        .IsUnique();

                    b.ToTable("SuitabilityConfiguration", null, t =>
                        {
                            t.HasCheckConstraint("CK_SuitabilityConfiguration_ConfigurationKey", "[ConfigurationKey] IN (N'Rainfall', N'Temperature', N'Humidity', N'SoilCompatibility', N'Highly Suitable', N'Suitable', N'Moderately Suitable', N'Unsuitable')");

                            t.HasCheckConstraint("CK_SuitabilityConfiguration_ConfigurationType", "[ConfigurationType] IN (N'FactorWeight', N'CategoryThreshold')");
                        });
                });

            modelBuilder.Entity("AnuradhapuraAI.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("AnuradhapuraAI.Domain.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("UserRole", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Registered User"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Agricultural Officer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Administrator"
                        });
                });

            modelBuilder.Entity("AnuradhapuraAI.Domain.Entities.CropEnvironmentalRequirement", b =>
                {
                    b.HasOne("AnuradhapuraAI.Domain.Entities.Crop", "Crop")
                        .WithMany("EnvironmentalRequirements")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Crop");
                });

            modelBuilder.Entity("AnuradhapuraAI.Domain.Entities.Recommendation", b =>
                {
                    b.HasOne("AnuradhapuraAI.Domain.Entities.User", "User")
                        .WithMany("Recommendations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("AnuradhapuraAI.Domain.Entities.RecommendationCrop", b =>
                {
                    b.HasOne("AnuradhapuraAI.Domain.Entities.Crop", "Crop")
                        .WithMany("RecommendationCrops")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnuradhapuraAI.Domain.Entities.Recommendation", "Recommendation")
                        .WithMany("RecommendationCrops")
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Crop");

                    b.Navigation("Recommendation");
                });

            modelBuilder.Entity("AnuradhapuraAI.Domain.Entities.RecommendationValidation", b =>
                {
                    b.HasOne("AnuradhapuraAI.Domain.Entities.User", "OfficerUser")
                        .WithMany("OfficerRecommendationValidations")
                        .HasForeignKey("OfficerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnuradhapuraAI.Domain.Entities.Recommendation", "Recommendation")
                        .WithMany("RecommendationValidations")
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OfficerUser");

                    b.Navigation("Recommendation");
                });

            modelBuilder.Entity("AnuradhapuraAI.Domain.Entities.SoilCompatibility", b =>
                {
                    b.HasOne("AnuradhapuraAI.Domain.Entities.Crop", "Crop")
                        .WithMany("SoilCompatibilities")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Crop");
                });

            modelBuilder.Entity("AnuradhapuraAI.Domain.Entities.SuitabilityConfiguration", b =>
                {
                    b.HasOne("AnuradhapuraAI.Domain.Entities.User", "UpdatedByUser")
                        .WithMany("UpdatedSuitabilityConfigurations")
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("AnuradhapuraAI.Domain.Entities.User", b =>
                {
                    b.HasOne("AnuradhapuraAI.Domain.Entities.UserRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AnuradhapuraAI.Domain.Entities.Crop", b =>
                {
                    b.Navigation("EnvironmentalRequirements");

                    b.Navigation("RecommendationCrops");

                    b.Navigation("SoilCompatibilities");
                });

            modelBuilder.Entity("AnuradhapuraAI.Domain.Entities.Recommendation", b =>
                {
                    b.Navigation("RecommendationCrops");

                    b.Navigation("RecommendationValidations");
                });

            modelBuilder.Entity("AnuradhapuraAI.Domain.Entities.User", b =>
                {
                    b.Navigation("OfficerRecommendationValidations");

                    b.Navigation("Recommendations");

                    b.Navigation("UpdatedSuitabilityConfigurations");
                });

            modelBuilder.Entity("AnuradhapuraAI.Domain.Entities.UserRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
